[package]
name = "ds210_final"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
dot = "0.1.4"
itertools = "0.10.0"

[[bin]]
name = "main"
path = "DS210_final/main.rs"